OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "*********************"
  base_url: "https://vip.apiyi.com/v1"
GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"